version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - dados:/var/lib/postgresql/data
    - ./scripts:/scripts
    - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql